name: Home Detector
description: A lightweight intrusion detector.
version: "0.0.1"
slug: homedetector
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
map:
  - share:rw
ports:
  10053/tcp: 10053
  10053/udp: 10053
options:
  debug: false
  networks: []
  unknown_ip_action: ignore
  detect_on_host_query: false
  soa_failure_action: ignore
  dns_blocking_mode: false
  learning_duration: 30
  resolvers: []
schema:
  debug: bool
  networks:
    - address: str
      type: str
  unknown_ip_action: str
  detect_on_host_query: bool
  soa_failure_action: str
  dns_blocking_mode: bool
  learning_duration: int
  resolvers:
    - server: str
      port: int
