name: Home Detector
description: A lightweight intrusion detector.
version: "0.0.1"
slug: homedetector
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
map:
  - share:rw
ports:
  10053/tcp: 10053
  10053/udp: 10053
options:
  debug: false
  networks:
    - 192.168.0.0/24:network
    - 192.168.10.10:host
    - 192.168.100.100-192.168.100.101:range
  unknown_ip_action: ignore
  soa_failure_action: ignore
  dns_blocking_mode: false
  learning_duration: 30
schema:
  debug: bool
  networks:
    - str
  unknown_ip_action: str
  soa_failure_action: str
  dns_blocking_mode: bool
  learning_duration: int
