name: Home Detector
description: A lightweight intrusion detector.
version: "0.0.1"
slug: homedetector
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
map:
  - addon_config:rw
  - share:rw
ports:
  10053/tcp: 53
  10053/udp: 53
  23/tcp: 23
  21/tcp:
  80/tcp:
ingress: true
ingress_entry: admin
panel_icon: mdi:incognito
panel_admin: true
options:
  networks: []
  resolvers: []
  learning_duration: 30
  unknown_ip_action: ignore
  detect_on_host_query: false
  soa_failure_action: ignore
  dns_blocking_mode: false
  custom_host_records: []
  debug: false
schema:
  networks:
    - address: str
      type: str
  resolvers:
    - server: str
      port: int
  learning_duration: int
  unknown_ip_action: str
  detect_on_host_query: bool
  soa_failure_action: str
  dns_blocking_mode: bool
  custom_host_records:
    - name: str
      address: str
  debug: bool
