arch:
- aarch64
- amd64
description: A lightweight intrusion detector.
homeassistant_api: true
ingress: true
ingress_entry: admin
init: false
map:
- addon_config:rw
name: Home Detector
options:
  custom_host_records: []
  debug: false
  detect_on_host_query: false
  dns_blocking_mode: false
  ha_notify: true
  networks: []
  resolvers: []
panel_admin: true
panel_icon: mdi:home-search-outline
ports:
  10053/tcp: 53
  10053/udp: 53
  1433/tcp: null
  21/tcp: null
  23/tcp: 23
  3306/tcp: null
  3389/tcp: null
  5000/tcp: null
  5060/tcp: null
  6379/tcp: null
  80/tcp: null
  8080/tcp: null
  9418/tcp: null
schema:
  custom_host_records:
  - address: str
    name: str
  debug: bool
  detect_on_host_query: bool
  dns_blocking_mode: bool
  ha_notify: bool
  ha_webhook_id: str?
  learning_duration: int?
  networks:
  - address: str
    type: str
  networks_ttl: int?
  resolvers:
  - port: int
    server: str
  soa_failure_action: str?
  unknown_ip_action: str?
slug: homedetector
startup: application
url: https://github.com/linickx/HomeDetector
version: 0.0.7
