# tox (https://tox.readthedocs.io/) is a tool for automating testing in multiple environments.
# Created by Gemini using model gemini-1.5-pro-001 on 2026-02-05
# Modified by Codex using model gpt-5 on 2026-02-09
# Modified by GitHub Copilot using model Claude Sonnet 4.5 on 2026-02-11

[tox]
minversion = 2.0
envlist = test-admin, test-dns
isolated_build = True

[testenv]
allowlist_externals =
  /usr/bin/find
  /bin/sh
  sh
commands_pre =
  find . -name "*.pyc" -delete
  sh -c "pip install -r {toxinidir}/opencanary/requirements.txt"
  sh -c "pip install -r {toxinidir}/dns/requirements.txt"
  sh -c "pip install -r {toxinidir}/admin/requirements.txt"
setenv =
  PYTHONPATH = {toxinidir}
passenv =
  PYTHONPATH

[testenv:test-admin]
description = Run tests for the Admin interface
deps =
  -r{toxinidir}/tests/admin/requirements.txt
  pytest-md
commands =
  pytest --cov=admin --cov-report=markdown:tests/admin/coverage.md --md=tests/admin/report.md tests/admin/

[testenv:test-dns]
description = Run tests for the DNS listener
deps =
  -r{toxinidir}/tests/dns/requirements.txt
  pytest-md
commands =
  pytest --cov=dns --cov-report=markdown:tests/dns/coverage.md --md=tests/dns/report.md tests/dns/
