# Created by GitHub Copilot CLI on 2026-02-06
name: Test Build

on:
  workflow_dispatch:

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master

  test-build:
    name: Test build for ${{ matrix.architecture }}
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image for ${{ matrix.architecture }}
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.architecture == 'amd64' && 'linux/amd64' || 'linux/arm64' }}
          push: false
          tags: homedetector:test-${{ matrix.architecture }}
